export { Map } from './map';
export type { MapContract, MapFeature } from './map.contract';
export type { MapProps } from './map.types';
export { useMapSlot } from './map-context';
export { recordsToMap } from './adapters/records.adapter';
export type { GeoRecord, GeoRecordsSource } from './adapters/records.adapter';
export { Caption } from './slots/Caption';
export type { CaptionProps } from './slots/Caption';
export { ZoomControls } from './slots/ZoomControls';
export { Summary } from './slots/Summary';
export type { SummaryProps } from './slots/Summary';
export { Legend } from './slots/Legend';
export type { LegendProps, LegendItem } from './slots/Legend';
export { StatusLegend } from './slots/StatusLegend';
export type { StatusLegendProps } from './slots/StatusLegend';
